apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpgcity-deployment
  namespace: jkpgcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkpgcity
  template:
    metadata:
      labels:
        app: jkpgcity
    spec:
      containers:
      - name: jkpgcity
        env:
        - name: DB_HOST
          value: "172.17.0.1"
        image: localhost:5001/jkpgcity